//
//  AppLogoKit.swift
//  ProjectName
//
//  Created by pavel on 08.11.2022.
//  Copyright © 2022 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

@IBDesignable
class AppLogoWithText: UIView {
    
    private let color: UIColor
    private let minusToneColor: UIColor
    
    init(color: UIColor, minusToneColor: UIColor) {
        self.color = color
        self.minusToneColor = minusToneColor
        
        super.init(frame: .zero)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func draw(_ rect: CGRect) {
        AppLogoKit.drawAppLogoText(frame: rect,
                                   color: color,
                                   minusToneColor: minusToneColor,
                                   resizing: .aspectFit)
    }
    
    override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
        setNeedsDisplay()
    }
}

@IBDesignable
class AppLogo: UIView {
    override func draw(_ rect: CGRect) {
        AppLogoKit.drawAppLogo(frame: rect, dark: traitCollection.userInterfaceStyle == .dark ? true : false, resizing: .aspectFit)
    }
    
    override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
        setNeedsDisplay()
    }
}

@IBDesignable
class AppLogoText: UIView {
    override func draw(_ rect: CGRect) {
        AppLogoKit.drawAppText(frame: rect, dark: traitCollection.userInterfaceStyle == .dark ? true : false, resizing: .aspectFit)
    }
    
    override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
        setNeedsDisplay()
    }
}

public class AppLogoKit : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawAppLogoText(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 3000, height: 500),
                                                    color: UIColor,
                                                    minusToneColor: UIColor,
                                                    resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 3000, height: 500), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 3000, y: resizedFrame.height / 500)
        
        //// Gradient Declarations
        let gradient = CGGradient(colorsSpace: nil,
                                  colors: [
                                    color.cgColor,
                                    color.blended(withFraction: 0.5, of: minusToneColor).cgColor,
                                    minusToneColor.cgColor
                                  ] as CFArray,
                                  locations: [0, 0.5, 1])!
        
        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.move(to: CGPoint(x: 131.54, y: 119.24))
        bezier3Path.addLine(to: CGPoint(x: 129.34, y: 123.93))
        bezier3Path.addCurve(to: CGPoint(x: 134.22, y: 137.61), controlPoint1: CGPoint(x: 126.93, y: 129.06), controlPoint2: CGPoint(x: 129.12, y: 135.17))
        bezier3Path.addLine(to: CGPoint(x: 162.02, y: 150.88))
        bezier3Path.addCurve(to: CGPoint(x: 129.16, y: 221.02), controlPoint1: CGPoint(x: 162.02, y: 150.88), controlPoint2: CGPoint(x: 141.03, y: 195.67))
        bezier3Path.addCurve(to: CGPoint(x: 121.2, y: 238), controlPoint1: CGPoint(x: 124.47, y: 231.02), controlPoint2: CGPoint(x: 121.2, y: 238))
        bezier3Path.addCurve(to: CGPoint(x: 137.19, y: 263.46), controlPoint1: CGPoint(x: 115.68, y: 249.79), controlPoint2: CGPoint(x: 124.18, y: 263.34))
        bezier3Path.addLine(to: CGPoint(x: 141.17, y: 263.5))
        bezier3Path.addCurve(to: CGPoint(x: 161.7, y: 263.7), controlPoint1: CGPoint(x: 141.17, y: 263.5), controlPoint2: CGPoint(x: 150.82, y: 263.59))
        bezier3Path.addCurve(to: CGPoint(x: 192.01, y: 264), controlPoint1: CGPoint(x: 175.81, y: 263.84), controlPoint2: CGPoint(x: 192.01, y: 264))
        bezier3Path.addLine(to: CGPoint(x: 191.64, y: 302.16))
        bezier3Path.addCurve(to: CGPoint(x: 191.63, y: 302.95), controlPoint1: CGPoint(x: 191.64, y: 302.16), controlPoint2: CGPoint(x: 191.64, y: 302.45))
        bezier3Path.addCurve(to: CGPoint(x: 191.5, y: 316.22), controlPoint1: CGPoint(x: 191.6, y: 305.91), controlPoint2: CGPoint(x: 191.5, y: 316.22))
        bezier3Path.addCurve(to: CGPoint(x: 213.63, y: 331.37), controlPoint1: CGPoint(x: 191.39, y: 327.71), controlPoint2: CGPoint(x: 202.97, y: 335.64))
        bezier3Path.addLine(to: CGPoint(x: 288.75, y: 301.27))
        bezier3Path.addCurve(to: CGPoint(x: 308.95, y: 292.12), controlPoint1: CGPoint(x: 292.41, y: 299.8), controlPoint2: CGPoint(x: 302.47, y: 295.56))
        bezier3Path.addCurve(to: CGPoint(x: 315.35, y: 283.12), controlPoint1: CGPoint(x: 313.03, y: 289.94), controlPoint2: CGPoint(x: 314.75, y: 287.27))
        bezier3Path.addCurve(to: CGPoint(x: 314.32, y: 276.47), controlPoint1: CGPoint(x: 315.69, y: 280.86), controlPoint2: CGPoint(x: 315.32, y: 278.54))
        bezier3Path.addLine(to: CGPoint(x: 311.74, y: 271.15))
        bezier3Path.addCurve(to: CGPoint(x: 298.58, y: 264.32), controlPoint1: CGPoint(x: 309.35, y: 266.21), controlPoint2: CGPoint(x: 303.99, y: 263.4))
        bezier3Path.addCurve(to: CGPoint(x: 271.64, y: 273.99), controlPoint1: CGPoint(x: 289.69, y: 265.81), controlPoint2: CGPoint(x: 278.23, y: 271.23))
        bezier3Path.addLine(to: CGPoint(x: 220.62, y: 295.32))
        bezier3Path.addLine(to: CGPoint(x: 220.14, y: 239.64))
        bezier3Path.addCurve(to: CGPoint(x: 215.47, y: 234.91), controlPoint1: CGPoint(x: 220.11, y: 237.06), controlPoint2: CGPoint(x: 218.05, y: 234.96))
        bezier3Path.addLine(to: CGPoint(x: 212.99, y: 234.85))
        bezier3Path.addLine(to: CGPoint(x: 160.65, y: 232.74))
        bezier3Path.addLine(to: CGPoint(x: 192.82, y: 165.06))
        bezier3Path.addLine(to: CGPoint(x: 222.17, y: 178.84))
        bezier3Path.addCurve(to: CGPoint(x: 234.71, y: 174.3), controlPoint1: CGPoint(x: 226.88, y: 181.05), controlPoint2: CGPoint(x: 232.49, y: 179.02))
        bezier3Path.addLine(to: CGPoint(x: 237.25, y: 168.89))
        bezier3Path.addCurve(to: CGPoint(x: 232.3, y: 155.19), controlPoint1: CGPoint(x: 239.66, y: 163.74), controlPoint2: CGPoint(x: 237.45, y: 157.6))
        bezier3Path.addLine(to: CGPoint(x: 145.24, y: 114.29))
        bezier3Path.addCurve(to: CGPoint(x: 131.54, y: 119.24), controlPoint1: CGPoint(x: 140.09, y: 111.87), controlPoint2: CGPoint(x: 133.96, y: 114.09))
        bezier3Path.close()
        bezier3Path.move(to: CGPoint(x: 103.83, y: 52.04))
        bezier3Path.addCurve(to: CGPoint(x: 164.95, y: 69.96), controlPoint1: CGPoint(x: 126.16, y: 52.55), controlPoint2: CGPoint(x: 147.08, y: 59.06))
        bezier3Path.addCurve(to: CGPoint(x: 227.34, y: 52.1), controlPoint1: CGPoint(x: 182.56, y: 57.85), controlPoint2: CGPoint(x: 204.21, y: 51.14))
        bezier3Path.addCurve(to: CGPoint(x: 294.03, y: 80.43), controlPoint1: CGPoint(x: 253.4, y: 53.17), controlPoint2: CGPoint(x: 276.76, y: 63.82))
        bezier3Path.addCurve(to: CGPoint(x: 321, y: 74.68), controlPoint1: CGPoint(x: 302.16, y: 76.55), controlPoint2: CGPoint(x: 311.34, y: 74.45))
        bezier3Path.addCurve(to: CGPoint(x: 378.05, y: 133.43), controlPoint1: CGPoint(x: 353.27, y: 75.44), controlPoint2: CGPoint(x: 378.81, y: 101.74))
        bezier3Path.addCurve(to: CGPoint(x: 372.3, y: 156.95), controlPoint1: CGPoint(x: 377.85, y: 141.86), controlPoint2: CGPoint(x: 375.79, y: 149.83))
        bezier3Path.addCurve(to: CGPoint(x: 403.98, y: 227.45), controlPoint1: CGPoint(x: 391.36, y: 174.66), controlPoint2: CGPoint(x: 403.45, y: 199.62))
        bezier3Path.addCurve(to: CGPoint(x: 384.31, y: 288.28), controlPoint1: CGPoint(x: 404.42, y: 250.18), controlPoint2: CGPoint(x: 397.05, y: 271.29))
        bezier3Path.addCurve(to: CGPoint(x: 401.11, y: 348.69), controlPoint1: CGPoint(x: 395, y: 306.09), controlPoint2: CGPoint(x: 401.11, y: 326.77))
        bezier3Path.addCurve(to: CGPoint(x: 401.04, y: 352.24), controlPoint1: CGPoint(x: 401.11, y: 349.88), controlPoint2: CGPoint(x: 401.09, y: 351.07))
        bezier3Path.addCurve(to: CGPoint(x: 225.71, y: 416.85), controlPoint1: CGPoint(x: 398.44, y: 440.29), controlPoint2: CGPoint(x: 287.62, y: 480.6))
        bezier3Path.addLine(to: CGPoint(x: 194.84, y: 385.03))
        bezier3Path.addCurve(to: CGPoint(x: 164.49, y: 373.82), controlPoint1: CGPoint(x: 186.99, y: 376.94), controlPoint2: CGPoint(x: 175.83, y: 372.95))
        bezier3Path.addCurve(to: CGPoint(x: 158.01, y: 374.07), controlPoint1: CGPoint(x: 162.35, y: 373.99), controlPoint2: CGPoint(x: 160.19, y: 374.07))
        bezier3Path.addLine(to: CGPoint(x: 76.02, y: 374.07))
        bezier3Path.addLine(to: CGPoint(x: 76.02, y: 286.24))
        bezier3Path.addCurve(to: CGPoint(x: 76.07, y: 283.4), controlPoint1: CGPoint(x: 76.02, y: 285.29), controlPoint2: CGPoint(x: 76.03, y: 284.34))
        bezier3Path.addCurve(to: CGPoint(x: 65.15, y: 256.85), controlPoint1: CGPoint(x: 76.42, y: 273.47), controlPoint2: CGPoint(x: 72.31, y: 263.88))
        bezier3Path.addLine(to: CGPoint(x: 30.27, y: 222.59))
        bezier3Path.addCurve(to: CGPoint(x: 36.77, y: 74.51), controlPoint1: CGPoint(x: -15.3, y: 177.84), controlPoint2: CGPoint(x: -5.58, y: 109.57))
        bezier3Path.addCurve(to: CGPoint(x: 100.22, y: 52), controlPoint1: CGPoint(x: 53.37, y: 60.77), controlPoint2: CGPoint(x: 74.97, y: 52.13))
        bezier3Path.addCurve(to: CGPoint(x: 103.83, y: 52.04), controlPoint1: CGPoint(x: 101.41, y: 52), controlPoint2: CGPoint(x: 102.62, y: 52))
        bezier3Path.close()
        color.setFill()
        bezier3Path.fill()


        //// Text 9 Drawing
        let text9Path = UIBezierPath()
        text9Path.move(to: CGPoint(x: 555.89, y: 347.54))
        text9Path.addCurve(to: CGPoint(x: 591.95, y: 419.21), controlPoint1: CGPoint(x: 556.22, y: 378.84), controlPoint2: CGPoint(x: 568.24, y: 402.73))
        text9Path.addCurve(to: CGPoint(x: 646.3, y: 435.02), controlPoint1: CGPoint(x: 607.44, y: 429.75), controlPoint2: CGPoint(x: 625.55, y: 435.02))
        text9Path.addCurve(to: CGPoint(x: 695.46, y: 426.37), controlPoint1: CGPoint(x: 663.76, y: 435.02), controlPoint2: CGPoint(x: 680.14, y: 432.14))
        text9Path.addCurve(to: CGPoint(x: 723.87, y: 404.38), controlPoint1: CGPoint(x: 710.78, y: 420.61), controlPoint2: CGPoint(x: 720.25, y: 413.28))
        text9Path.addCurve(to: CGPoint(x: 708.06, y: 378.18), controlPoint1: CGPoint(x: 719.26, y: 396.47), controlPoint2: CGPoint(x: 713.99, y: 387.74))
        text9Path.addCurve(to: CGPoint(x: 694.97, y: 356.43), controlPoint1: CGPoint(x: 702.13, y: 368.63), controlPoint2: CGPoint(x: 697.77, y: 361.38))
        text9Path.addCurve(to: CGPoint(x: 688.3, y: 343.58), controlPoint1: CGPoint(x: 692.17, y: 351.49), controlPoint2: CGPoint(x: 689.94, y: 347.21))
        text9Path.addCurve(to: CGPoint(x: 671.75, y: 355.2), controlPoint1: CGPoint(x: 684.67, y: 348.53), controlPoint2: CGPoint(x: 679.16, y: 352.4))
        text9Path.addCurve(to: CGPoint(x: 650.75, y: 357.42), controlPoint1: CGPoint(x: 664.33, y: 358), controlPoint2: CGPoint(x: 657.34, y: 358.74))
        text9Path.addCurve(to: CGPoint(x: 635.93, y: 347.04), controlPoint1: CGPoint(x: 643.5, y: 356.1), controlPoint2: CGPoint(x: 638.56, y: 352.65))
        text9Path.addCurve(to: CGPoint(x: 632.47, y: 318.87), controlPoint1: CGPoint(x: 633.29, y: 341.44), controlPoint2: CGPoint(x: 632.14, y: 332.05))
        text9Path.addLine(to: CGPoint(x: 632.47, y: 233.86))
        text9Path.addLine(to: CGPoint(x: 701.14, y: 233.86))
        text9Path.addLine(to: CGPoint(x: 701.14, y: 163.18))
        text9Path.addLine(to: CGPoint(x: 631.97, y: 162.68))
        text9Path.addLine(to: CGPoint(x: 632.96, y: 61.85))
        text9Path.addLine(to: CGPoint(x: 557.86, y: 111.77))
        text9Path.addLine(to: CGPoint(x: 557.86, y: 165.15))
        text9Path.addLine(to: CGPoint(x: 505.99, y: 165.15))
        text9Path.addLine(to: CGPoint(x: 505, y: 232.87))
        text9Path.addLine(to: CGPoint(x: 555.89, y: 233.36))
        text9Path.addLine(to: CGPoint(x: 555.89, y: 347.54))
        text9Path.close()
        text9Path.move(to: CGPoint(x: 745.61, y: 66.79))
        text9Path.addLine(to: CGPoint(x: 745.61, y: 433.54))
        text9Path.addLine(to: CGPoint(x: 825.64, y: 434.53))
        text9Path.addLine(to: CGPoint(x: 826.14, y: 291.19))
        text9Path.addCurve(to: CGPoint(x: 830.09, y: 268.95), controlPoint1: CGPoint(x: 826.14, y: 283.28), controlPoint2: CGPoint(x: 827.46, y: 275.87))
        text9Path.addCurve(to: CGPoint(x: 840.96, y: 251.4), controlPoint1: CGPoint(x: 832.73, y: 262.03), controlPoint2: CGPoint(x: 836.35, y: 256.18))
        text9Path.addCurve(to: CGPoint(x: 857.51, y: 240.03), controlPoint1: CGPoint(x: 845.57, y: 246.62), controlPoint2: CGPoint(x: 851.09, y: 242.84))
        text9Path.addCurve(to: CGPoint(x: 878.51, y: 235.83), controlPoint1: CGPoint(x: 863.93, y: 237.23), controlPoint2: CGPoint(x: 870.93, y: 235.83))
        text9Path.addCurve(to: CGPoint(x: 914.58, y: 250.66), controlPoint1: CGPoint(x: 893.66, y: 236.16), controlPoint2: CGPoint(x: 905.68, y: 241.11))
        text9Path.addCurve(to: CGPoint(x: 927.91, y: 288.23), controlPoint1: CGPoint(x: 923.47, y: 260.22), controlPoint2: CGPoint(x: 927.91, y: 272.74))
        text9Path.addLine(to: CGPoint(x: 927.91, y: 433.54))
        text9Path.addLine(to: CGPoint(x: 1006.96, y: 434.53))
        text9Path.addLine(to: CGPoint(x: 1006.96, y: 273.89))
        text9Path.addCurve(to: CGPoint(x: 978.56, y: 199.26), controlPoint1: CGPoint(x: 1006.96, y: 243.91), controlPoint2: CGPoint(x: 997.49, y: 219.03))
        text9Path.addCurve(to: CGPoint(x: 904.69, y: 169.6), controlPoint1: CGPoint(x: 959.62, y: 179.49), controlPoint2: CGPoint(x: 935, y: 169.6))
        text9Path.addCurve(to: CGPoint(x: 823.17, y: 200.74), controlPoint1: CGPoint(x: 865.17, y: 169.6), controlPoint2: CGPoint(x: 838, y: 179.98))
        text9Path.addLine(to: CGPoint(x: 823.17, y: 66.79))
        text9Path.addLine(to: CGPoint(x: 745.61, y: 66.79))
        text9Path.close()
        text9Path.move(to: CGPoint(x: 1041.05, y: 166.64))
        text9Path.addLine(to: CGPoint(x: 1041.05, y: 433.54))
        text9Path.addLine(to: CGPoint(x: 1120.6, y: 433.54))
        text9Path.addLine(to: CGPoint(x: 1120.6, y: 166.64))
        text9Path.addLine(to: CGPoint(x: 1041.05, y: 166.64))
        text9Path.close()
        text9Path.move(to: CGPoint(x: 1080.58, y: 141.92))
        text9Path.addCurve(to: CGPoint(x: 1115.41, y: 128.82), controlPoint1: CGPoint(x: 1094.74, y: 141.92), controlPoint2: CGPoint(x: 1106.35, y: 137.56))
        text9Path.addCurve(to: CGPoint(x: 1129, y: 94.97), controlPoint1: CGPoint(x: 1124.47, y: 120.09), controlPoint2: CGPoint(x: 1129, y: 108.81))
        text9Path.addCurve(to: CGPoint(x: 1126.77, y: 79.89), controlPoint1: CGPoint(x: 1129, y: 89.69), controlPoint2: CGPoint(x: 1128.26, y: 84.67))
        text9Path.addCurve(to: CGPoint(x: 1120.1, y: 67.29), controlPoint1: CGPoint(x: 1125.29, y: 75.11), controlPoint2: CGPoint(x: 1123.07, y: 70.91))
        text9Path.addCurve(to: CGPoint(x: 1109.73, y: 57.65), controlPoint1: CGPoint(x: 1117.14, y: 63.66), controlPoint2: CGPoint(x: 1113.68, y: 60.45))
        text9Path.addCurve(to: CGPoint(x: 1096.39, y: 51.22), controlPoint1: CGPoint(x: 1105.78, y: 54.85), controlPoint2: CGPoint(x: 1101.33, y: 52.71))
        text9Path.addCurve(to: CGPoint(x: 1080.58, y: 49), controlPoint1: CGPoint(x: 1091.45, y: 49.74), controlPoint2: CGPoint(x: 1086.18, y: 49))
        text9Path.addCurve(to: CGPoint(x: 1046, y: 61.85), controlPoint1: CGPoint(x: 1066.42, y: 49), controlPoint2: CGPoint(x: 1054.89, y: 53.28))
        text9Path.addCurve(to: CGPoint(x: 1032.66, y: 94.97), controlPoint1: CGPoint(x: 1037.1, y: 70.42), controlPoint2: CGPoint(x: 1032.66, y: 81.46))
        text9Path.addCurve(to: CGPoint(x: 1036.11, y: 114), controlPoint1: CGPoint(x: 1032.66, y: 101.89), controlPoint2: CGPoint(x: 1033.81, y: 108.23))
        text9Path.addCurve(to: CGPoint(x: 1046, y: 128.82), controlPoint1: CGPoint(x: 1038.42, y: 119.76), controlPoint2: CGPoint(x: 1041.71, y: 124.71))
        text9Path.addCurve(to: CGPoint(x: 1061.31, y: 138.46), controlPoint1: CGPoint(x: 1050.28, y: 132.94), controlPoint2: CGPoint(x: 1055.38, y: 136.16))
        text9Path.addCurve(to: CGPoint(x: 1080.58, y: 141.92), controlPoint1: CGPoint(x: 1067.24, y: 140.77), controlPoint2: CGPoint(x: 1073.66, y: 141.92))
        text9Path.close()
        text9Path.move(to: CGPoint(x: 1147.77, y: 433.54))
        text9Path.addLine(to: CGPoint(x: 1224.35, y: 433.54))
        text9Path.addLine(to: CGPoint(x: 1224.35, y: 284.77))
        text9Path.addCurve(to: CGPoint(x: 1228.06, y: 262.52), controlPoint1: CGPoint(x: 1224.35, y: 276.53), controlPoint2: CGPoint(x: 1225.59, y: 269.11))
        text9Path.addCurve(to: CGPoint(x: 1238.68, y: 246.21), controlPoint1: CGPoint(x: 1230.53, y: 255.93), controlPoint2: CGPoint(x: 1234.07, y: 250.5))
        text9Path.addCurve(to: CGPoint(x: 1254.74, y: 236.57), controlPoint1: CGPoint(x: 1243.29, y: 241.93), controlPoint2: CGPoint(x: 1248.64, y: 238.72))
        text9Path.addCurve(to: CGPoint(x: 1274.74, y: 233.36), controlPoint1: CGPoint(x: 1260.83, y: 234.43), controlPoint2: CGPoint(x: 1267.5, y: 233.36))
        text9Path.addCurve(to: CGPoint(x: 1308.59, y: 246.21), controlPoint1: CGPoint(x: 1289.24, y: 233.36), controlPoint2: CGPoint(x: 1300.52, y: 237.65))
        text9Path.addCurve(to: CGPoint(x: 1320.69, y: 282.79), controlPoint1: CGPoint(x: 1316.66, y: 254.78), controlPoint2: CGPoint(x: 1320.69, y: 266.97))
        text9Path.addLine(to: CGPoint(x: 1320.69, y: 433.54))
        text9Path.addLine(to: CGPoint(x: 1398.26, y: 433.54))
        text9Path.addLine(to: CGPoint(x: 1398.26, y: 268.45))
        text9Path.addCurve(to: CGPoint(x: 1363.68, y: 188.88), controlPoint1: CGPoint(x: 1398.26, y: 236.16), controlPoint2: CGPoint(x: 1386.73, y: 209.64))
        text9Path.addCurve(to: CGPoint(x: 1273.26, y: 157.74), controlPoint1: CGPoint(x: 1340.62, y: 168.12), controlPoint2: CGPoint(x: 1310.48, y: 157.74))
        text9Path.addCurve(to: CGPoint(x: 1255.72, y: 158.73), controlPoint1: CGPoint(x: 1267.66, y: 157.74), controlPoint2: CGPoint(x: 1261.82, y: 158.07))
        text9Path.addCurve(to: CGPoint(x: 1233.74, y: 163.67), controlPoint1: CGPoint(x: 1249.63, y: 159.39), controlPoint2: CGPoint(x: 1242.3, y: 161.03))
        text9Path.addCurve(to: CGPoint(x: 1209.53, y: 173.56), controlPoint1: CGPoint(x: 1225.17, y: 166.31), controlPoint2: CGPoint(x: 1217.1, y: 169.6))
        text9Path.addCurve(to: CGPoint(x: 1186.55, y: 190.36), controlPoint1: CGPoint(x: 1201.95, y: 177.51), controlPoint2: CGPoint(x: 1194.3, y: 183.11))
        text9Path.addCurve(to: CGPoint(x: 1166.55, y: 215.57), controlPoint1: CGPoint(x: 1178.81, y: 197.61), controlPoint2: CGPoint(x: 1172.14, y: 206.01))
        text9Path.addCurve(to: CGPoint(x: 1153.21, y: 251.16), controlPoint1: CGPoint(x: 1160.95, y: 225.12), controlPoint2: CGPoint(x: 1156.5, y: 236.99))
        text9Path.addCurve(to: CGPoint(x: 1148.27, y: 297.62), controlPoint1: CGPoint(x: 1149.91, y: 265.32), controlPoint2: CGPoint(x: 1148.27, y: 280.81))
        text9Path.addLine(to: CGPoint(x: 1147.77, y: 433.54))
        text9Path.close()
        text9Path.move(to: CGPoint(x: 1426.42, y: 433.54))
        text9Path.addLine(to: CGPoint(x: 1502.01, y: 434.53))
        text9Path.addLine(to: CGPoint(x: 1503, y: 365.33))
        text9Path.addLine(to: CGPoint(x: 1532.15, y: 340.12))
        text9Path.addCurve(to: CGPoint(x: 1551.66, y: 368.3), controlPoint1: CGPoint(x: 1534.46, y: 342.76), controlPoint2: CGPoint(x: 1540.96, y: 352.15))
        text9Path.addCurve(to: CGPoint(x: 1581.8, y: 413.28), controlPoint1: CGPoint(x: 1562.37, y: 384.44), controlPoint2: CGPoint(x: 1572.42, y: 399.44))
        text9Path.addCurve(to: CGPoint(x: 1596.87, y: 433.54), controlPoint1: CGPoint(x: 1591.19, y: 427.11), controlPoint2: CGPoint(x: 1596.21, y: 433.87))
        text9Path.addCurve(to: CGPoint(x: 1607.25, y: 432.8), controlPoint1: CGPoint(x: 1597.53, y: 433.21), controlPoint2: CGPoint(x: 1600.99, y: 432.96))
        text9Path.addCurve(to: CGPoint(x: 1629.97, y: 432.3), controlPoint1: CGPoint(x: 1613.5, y: 432.63), controlPoint2: CGPoint(x: 1621.08, y: 432.47))
        text9Path.addCurve(to: CGPoint(x: 1655.91, y: 432.06), controlPoint1: CGPoint(x: 1638.87, y: 432.14), controlPoint2: CGPoint(x: 1647.51, y: 432.06))
        text9Path.addCurve(to: CGPoint(x: 1677.9, y: 432.06), controlPoint1: CGPoint(x: 1664.31, y: 432.06), controlPoint2: CGPoint(x: 1671.64, y: 432.06))
        text9Path.addCurve(to: CGPoint(x: 1686.79, y: 432.55), controlPoint1: CGPoint(x: 1684.16, y: 432.06), controlPoint2: CGPoint(x: 1687.12, y: 432.22))
        text9Path.addLine(to: CGPoint(x: 1587.48, y: 289.21))
        text9Path.addLine(to: CGPoint(x: 1690.25, y: 168.61))
        text9Path.addLine(to: CGPoint(x: 1596.87, y: 168.12))
        text9Path.addLine(to: CGPoint(x: 1501.52, y: 267.96))
        text9Path.addLine(to: CGPoint(x: 1502.01, y: 66.79))
        text9Path.addLine(to: CGPoint(x: 1426.42, y: 66.79))
        text9Path.addLine(to: CGPoint(x: 1426.42, y: 433.54))
        text9Path.close()
        text9Path.move(to: CGPoint(x: 1888.37, y: 432.06))
        text9Path.addLine(to: CGPoint(x: 1935.3, y: 257.58))
        text9Path.addLine(to: CGPoint(x: 1973.34, y: 432.06))
        text9Path.addLine(to: CGPoint(x: 2067.22, y: 432.06))
        text9Path.addLine(to: CGPoint(x: 2144.29, y: 167.13))
        text9Path.addLine(to: CGPoint(x: 2069.69, y: 167.13))
        text9Path.addLine(to: CGPoint(x: 2021.27, y: 334.19))
        text9Path.addLine(to: CGPoint(x: 1981.74, y: 166.64))
        text9Path.addLine(to: CGPoint(x: 1887.38, y: 167.13))
        text9Path.addLine(to: CGPoint(x: 1842.42, y: 334.69))
        text9Path.addLine(to: CGPoint(x: 1794.99, y: 166.64))
        text9Path.addLine(to: CGPoint(x: 1717.92, y: 167.13))
        text9Path.addLine(to: CGPoint(x: 1794.5, y: 432.06))
        text9Path.addLine(to: CGPoint(x: 1888.37, y: 432.06))
        text9Path.close()
        text9Path.move(to: CGPoint(x: 2175.91, y: 66.79))
        text9Path.addLine(to: CGPoint(x: 2175.91, y: 433.54))
        text9Path.addLine(to: CGPoint(x: 2255.95, y: 434.53))
        text9Path.addLine(to: CGPoint(x: 2256.44, y: 291.19))
        text9Path.addCurve(to: CGPoint(x: 2260.39, y: 268.95), controlPoint1: CGPoint(x: 2256.44, y: 283.28), controlPoint2: CGPoint(x: 2257.76, y: 275.87))
        text9Path.addCurve(to: CGPoint(x: 2271.26, y: 251.4), controlPoint1: CGPoint(x: 2263.03, y: 262.03), controlPoint2: CGPoint(x: 2266.65, y: 256.18))
        text9Path.addCurve(to: CGPoint(x: 2287.81, y: 240.03), controlPoint1: CGPoint(x: 2275.87, y: 246.62), controlPoint2: CGPoint(x: 2281.39, y: 242.84))
        text9Path.addCurve(to: CGPoint(x: 2308.81, y: 235.83), controlPoint1: CGPoint(x: 2294.24, y: 237.23), controlPoint2: CGPoint(x: 2301.24, y: 235.83))
        text9Path.addCurve(to: CGPoint(x: 2344.88, y: 250.66), controlPoint1: CGPoint(x: 2323.96, y: 236.16), controlPoint2: CGPoint(x: 2335.98, y: 241.11))
        text9Path.addCurve(to: CGPoint(x: 2358.22, y: 288.23), controlPoint1: CGPoint(x: 2353.77, y: 260.22), controlPoint2: CGPoint(x: 2358.22, y: 272.74))
        text9Path.addLine(to: CGPoint(x: 2358.22, y: 433.54))
        text9Path.addLine(to: CGPoint(x: 2437.27, y: 434.53))
        text9Path.addLine(to: CGPoint(x: 2437.27, y: 273.89))
        text9Path.addCurve(to: CGPoint(x: 2408.86, y: 199.26), controlPoint1: CGPoint(x: 2437.27, y: 243.91), controlPoint2: CGPoint(x: 2427.8, y: 219.03))
        text9Path.addCurve(to: CGPoint(x: 2335, y: 169.6), controlPoint1: CGPoint(x: 2389.92, y: 179.49), controlPoint2: CGPoint(x: 2365.3, y: 169.6))
        text9Path.addCurve(to: CGPoint(x: 2253.48, y: 200.74), controlPoint1: CGPoint(x: 2295.47, y: 169.6), controlPoint2: CGPoint(x: 2268.3, y: 179.98))
        text9Path.addLine(to: CGPoint(x: 2253.48, y: 66.79))
        text9Path.addLine(to: CGPoint(x: 2175.91, y: 66.79))
        text9Path.close()
        text9Path.move(to: CGPoint(x: 2760.88, y: 306.02))
        text9Path.addCurve(to: CGPoint(x: 2754.45, y: 255.36), controlPoint1: CGPoint(x: 2760.55, y: 287.24), controlPoint2: CGPoint(x: 2758.4, y: 270.35))
        text9Path.addCurve(to: CGPoint(x: 2739.88, y: 217.79), controlPoint1: CGPoint(x: 2750.5, y: 240.36), controlPoint2: CGPoint(x: 2745.64, y: 227.84))
        text9Path.addCurve(to: CGPoint(x: 2718.39, y: 191.35), controlPoint1: CGPoint(x: 2734.11, y: 207.74), controlPoint2: CGPoint(x: 2726.95, y: 198.93))
        text9Path.addCurve(to: CGPoint(x: 2692.94, y: 173.8), controlPoint1: CGPoint(x: 2709.82, y: 183.77), controlPoint2: CGPoint(x: 2701.34, y: 177.92))
        text9Path.addCurve(to: CGPoint(x: 2664.29, y: 164.16), controlPoint1: CGPoint(x: 2684.54, y: 169.68), controlPoint2: CGPoint(x: 2674.99, y: 166.47))
        text9Path.addCurve(to: CGPoint(x: 2635.63, y: 159.47), controlPoint1: CGPoint(x: 2653.58, y: 161.86), controlPoint2: CGPoint(x: 2644.03, y: 160.29))
        text9Path.addCurve(to: CGPoint(x: 2607.22, y: 158.23), controlPoint1: CGPoint(x: 2627.23, y: 158.65), controlPoint2: CGPoint(x: 2617.76, y: 158.23))
        text9Path.addCurve(to: CGPoint(x: 2539.78, y: 176.52), controlPoint1: CGPoint(x: 2583.51, y: 158.23), controlPoint2: CGPoint(x: 2561.03, y: 164.33))
        text9Path.addCurve(to: CGPoint(x: 2488.15, y: 227.92), controlPoint1: CGPoint(x: 2518.54, y: 188.71), controlPoint2: CGPoint(x: 2501.33, y: 205.85))
        text9Path.addCurve(to: CGPoint(x: 2468.39, y: 301.08), controlPoint1: CGPoint(x: 2474.98, y: 250), controlPoint2: CGPoint(x: 2468.39, y: 274.39))
        text9Path.addCurve(to: CGPoint(x: 2504.95, y: 399.19), controlPoint1: CGPoint(x: 2468.39, y: 341.28), controlPoint2: CGPoint(x: 2480.58, y: 373.98))
        text9Path.addCurve(to: CGPoint(x: 2596.35, y: 437), controlPoint1: CGPoint(x: 2529.33, y: 424.4), controlPoint2: CGPoint(x: 2559.79, y: 437))
        text9Path.addCurve(to: CGPoint(x: 2649.71, y: 427.11), controlPoint1: CGPoint(x: 2614.47, y: 437), controlPoint2: CGPoint(x: 2632.26, y: 433.7))
        text9Path.addCurve(to: CGPoint(x: 2683.31, y: 404.38), controlPoint1: CGPoint(x: 2667.17, y: 420.52), controlPoint2: CGPoint(x: 2678.37, y: 412.95))
        text9Path.addLine(to: CGPoint(x: 2683.31, y: 430.57))
        text9Path.addLine(to: CGPoint(x: 2760.88, y: 430.57))
        text9Path.addLine(to: CGPoint(x: 2760.88, y: 306.02))
        text9Path.close()
        text9Path.move(to: CGPoint(x: 2643.78, y: 362.37))
        text9Path.addCurve(to: CGPoint(x: 2616.86, y: 367.31), controlPoint1: CGPoint(x: 2635.55, y: 365.66), controlPoint2: CGPoint(x: 2626.57, y: 367.31))
        text9Path.addCurve(to: CGPoint(x: 2589.68, y: 362.37), controlPoint1: CGPoint(x: 2607.14, y: 367.31), controlPoint2: CGPoint(x: 2598.08, y: 365.66))
        text9Path.addCurve(to: CGPoint(x: 2568.44, y: 348.53), controlPoint1: CGPoint(x: 2581.28, y: 359.07), controlPoint2: CGPoint(x: 2574.2, y: 354.46))
        text9Path.addCurve(to: CGPoint(x: 2554.61, y: 327.03), controlPoint1: CGPoint(x: 2562.68, y: 342.59), controlPoint2: CGPoint(x: 2558.06, y: 335.43))
        text9Path.addCurve(to: CGPoint(x: 2549.42, y: 300.09), controlPoint1: CGPoint(x: 2551.15, y: 318.62), controlPoint2: CGPoint(x: 2549.42, y: 309.64))
        text9Path.addCurve(to: CGPoint(x: 2568.44, y: 251.9), controlPoint1: CGPoint(x: 2549.42, y: 280.65), controlPoint2: CGPoint(x: 2555.76, y: 264.58))
        text9Path.addCurve(to: CGPoint(x: 2616.61, y: 232.87), controlPoint1: CGPoint(x: 2581.12, y: 239.21), controlPoint2: CGPoint(x: 2597.18, y: 232.87))
        text9Path.addCurve(to: CGPoint(x: 2643.78, y: 238.06), controlPoint1: CGPoint(x: 2626.49, y: 232.87), controlPoint2: CGPoint(x: 2635.55, y: 234.6))
        text9Path.addCurve(to: CGPoint(x: 2665.03, y: 252.14), controlPoint1: CGPoint(x: 2652.02, y: 241.52), controlPoint2: CGPoint(x: 2659.1, y: 246.21))
        text9Path.addCurve(to: CGPoint(x: 2678.86, y: 273.4), controlPoint1: CGPoint(x: 2670.96, y: 258.08), controlPoint2: CGPoint(x: 2675.57, y: 265.16))
        text9Path.addCurve(to: CGPoint(x: 2683.8, y: 300.09), controlPoint1: CGPoint(x: 2682.16, y: 281.64), controlPoint2: CGPoint(x: 2683.8, y: 290.53))
        text9Path.addCurve(to: CGPoint(x: 2678.86, y: 327.03), controlPoint1: CGPoint(x: 2683.8, y: 309.64), controlPoint2: CGPoint(x: 2682.16, y: 318.62))
        text9Path.addCurve(to: CGPoint(x: 2665.03, y: 348.53), controlPoint1: CGPoint(x: 2675.57, y: 335.43), controlPoint2: CGPoint(x: 2670.96, y: 342.59))
        text9Path.addCurve(to: CGPoint(x: 2643.78, y: 362.37), controlPoint1: CGPoint(x: 2659.1, y: 354.46), controlPoint2: CGPoint(x: 2652.02, y: 359.07))
        text9Path.close()
        text9Path.move(to: CGPoint(x: 2832.02, y: 347.54))
        text9Path.addCurve(to: CGPoint(x: 2868.09, y: 419.21), controlPoint1: CGPoint(x: 2832.35, y: 378.84), controlPoint2: CGPoint(x: 2844.37, y: 402.73))
        text9Path.addCurve(to: CGPoint(x: 2922.43, y: 435.02), controlPoint1: CGPoint(x: 2883.57, y: 429.75), controlPoint2: CGPoint(x: 2901.68, y: 435.02))
        text9Path.addCurve(to: CGPoint(x: 2971.59, y: 426.37), controlPoint1: CGPoint(x: 2939.89, y: 435.02), controlPoint2: CGPoint(x: 2956.28, y: 432.14))
        text9Path.addCurve(to: CGPoint(x: 3000, y: 404.38), controlPoint1: CGPoint(x: 2986.91, y: 420.61), controlPoint2: CGPoint(x: 2996.38, y: 413.28))
        text9Path.addCurve(to: CGPoint(x: 2984.19, y: 378.18), controlPoint1: CGPoint(x: 2995.39, y: 396.47), controlPoint2: CGPoint(x: 2990.12, y: 387.74))
        text9Path.addCurve(to: CGPoint(x: 2971.1, y: 356.43), controlPoint1: CGPoint(x: 2978.26, y: 368.63), controlPoint2: CGPoint(x: 2973.9, y: 361.38))
        text9Path.addCurve(to: CGPoint(x: 2964.43, y: 343.58), controlPoint1: CGPoint(x: 2968.3, y: 351.49), controlPoint2: CGPoint(x: 2966.07, y: 347.21))
        text9Path.addCurve(to: CGPoint(x: 2947.88, y: 355.2), controlPoint1: CGPoint(x: 2960.8, y: 348.53), controlPoint2: CGPoint(x: 2955.29, y: 352.4))
        text9Path.addCurve(to: CGPoint(x: 2926.88, y: 357.42), controlPoint1: CGPoint(x: 2940.47, y: 358), controlPoint2: CGPoint(x: 2933.47, y: 358.74))
        text9Path.addCurve(to: CGPoint(x: 2912.06, y: 347.04), controlPoint1: CGPoint(x: 2919.63, y: 356.1), controlPoint2: CGPoint(x: 2914.69, y: 352.65))
        text9Path.addCurve(to: CGPoint(x: 2908.6, y: 318.87), controlPoint1: CGPoint(x: 2909.42, y: 341.44), controlPoint2: CGPoint(x: 2908.27, y: 332.05))
        text9Path.addLine(to: CGPoint(x: 2908.6, y: 233.86))
        text9Path.addLine(to: CGPoint(x: 2977.27, y: 233.86))
        text9Path.addLine(to: CGPoint(x: 2977.27, y: 163.18))
        text9Path.addLine(to: CGPoint(x: 2908.1, y: 162.68))
        text9Path.addLine(to: CGPoint(x: 2909.09, y: 61.85))
        text9Path.addLine(to: CGPoint(x: 2834, y: 111.77))
        text9Path.addLine(to: CGPoint(x: 2834, y: 165.15))
        text9Path.addLine(to: CGPoint(x: 2782.12, y: 165.15))
        text9Path.addLine(to: CGPoint(x: 2781.13, y: 232.87))
        text9Path.addLine(to: CGPoint(x: 2832.02, y: 233.36))
        text9Path.addLine(to: CGPoint(x: 2832.02, y: 347.54))
        text9Path.close()
        context.saveGState()
        text9Path.addClip()
        context.drawLinearGradient(gradient, start: CGPoint(x: 505, y: 243), end: CGPoint(x: 3000, y: 243), options: [])
        context.restoreGState()
        
        context.restoreGState()

    }

    @objc dynamic public class func drawAppLogo(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 400, height: 400), dark: Bool = false, resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 400, height: 400), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 400, y: resizedFrame.height / 400)


        //// Color Declarations
        let vermillion = UIColor(red: 0.890, green: 0.259, blue: 0.204, alpha: 1.000)

        //// icon Drawing
        let iconPath = UIBezierPath()
        iconPath.move(to: CGPoint(x: 130.24, y: 71.56))
        iconPath.addLine(to: CGPoint(x: 128.06, y: 76.21))
        iconPath.addCurve(to: CGPoint(x: 132.9, y: 89.74), controlPoint1: CGPoint(x: 125.68, y: 81.28), controlPoint2: CGPoint(x: 127.84, y: 87.33))
        iconPath.addLine(to: CGPoint(x: 160.42, y: 102.88))
        iconPath.addCurve(to: CGPoint(x: 127.88, y: 172.31), controlPoint1: CGPoint(x: 160.42, y: 102.88), controlPoint2: CGPoint(x: 139.64, y: 147.22))
        iconPath.addCurve(to: CGPoint(x: 120, y: 189.12), controlPoint1: CGPoint(x: 123.24, y: 182.22), controlPoint2: CGPoint(x: 120, y: 189.12))
        iconPath.addCurve(to: CGPoint(x: 135.83, y: 214.33), controlPoint1: CGPoint(x: 114.53, y: 200.79), controlPoint2: CGPoint(x: 122.96, y: 214.21))
        iconPath.addLine(to: CGPoint(x: 139.77, y: 214.36))
        iconPath.addCurve(to: CGPoint(x: 160.1, y: 214.56), controlPoint1: CGPoint(x: 139.77, y: 214.36), controlPoint2: CGPoint(x: 149.32, y: 214.46))
        iconPath.addCurve(to: CGPoint(x: 190.11, y: 214.86), controlPoint1: CGPoint(x: 174.07, y: 214.7), controlPoint2: CGPoint(x: 190.11, y: 214.86))
        iconPath.addLine(to: CGPoint(x: 189.74, y: 252.64))
        iconPath.addCurve(to: CGPoint(x: 189.74, y: 253.41), controlPoint1: CGPoint(x: 189.74, y: 252.64), controlPoint2: CGPoint(x: 189.74, y: 252.92))
        iconPath.addCurve(to: CGPoint(x: 189.6, y: 266.55), controlPoint1: CGPoint(x: 189.71, y: 256.34), controlPoint2: CGPoint(x: 189.6, y: 266.55))
        iconPath.addCurve(to: CGPoint(x: 211.52, y: 281.55), controlPoint1: CGPoint(x: 189.49, y: 277.93), controlPoint2: CGPoint(x: 200.96, y: 285.78))
        iconPath.addLine(to: CGPoint(x: 285.89, y: 251.75))
        iconPath.addCurve(to: CGPoint(x: 305.89, y: 242.69), controlPoint1: CGPoint(x: 289.51, y: 250.3), controlPoint2: CGPoint(x: 299.48, y: 246.1))
        iconPath.addCurve(to: CGPoint(x: 312.23, y: 233.78), controlPoint1: CGPoint(x: 309.93, y: 240.53), controlPoint2: CGPoint(x: 311.63, y: 237.89))
        iconPath.addCurve(to: CGPoint(x: 311.21, y: 227.2), controlPoint1: CGPoint(x: 312.56, y: 231.55), controlPoint2: CGPoint(x: 312.2, y: 229.25))
        iconPath.addLine(to: CGPoint(x: 308.66, y: 221.94))
        iconPath.addCurve(to: CGPoint(x: 295.62, y: 215.17), controlPoint1: CGPoint(x: 306.28, y: 217.04), controlPoint2: CGPoint(x: 300.98, y: 214.27))
        iconPath.addCurve(to: CGPoint(x: 268.95, y: 224.75), controlPoint1: CGPoint(x: 286.82, y: 216.65), controlPoint2: CGPoint(x: 275.48, y: 222.02))
        iconPath.addLine(to: CGPoint(x: 218.44, y: 245.86))
        iconPath.addLine(to: CGPoint(x: 217.96, y: 190.75))
        iconPath.addCurve(to: CGPoint(x: 213.33, y: 186.06), controlPoint1: CGPoint(x: 217.93, y: 188.19), controlPoint2: CGPoint(x: 215.89, y: 186.11))
        iconPath.addLine(to: CGPoint(x: 210.88, y: 186.01))
        iconPath.addLine(to: CGPoint(x: 159.06, y: 183.91))
        iconPath.addLine(to: CGPoint(x: 190.91, y: 116.92))
        iconPath.addLine(to: CGPoint(x: 219.97, y: 130.56))
        iconPath.addCurve(to: CGPoint(x: 232.38, y: 126.07), controlPoint1: CGPoint(x: 224.64, y: 132.75), controlPoint2: CGPoint(x: 230.19, y: 130.74))
        iconPath.addLine(to: CGPoint(x: 234.9, y: 120.71))
        iconPath.addCurve(to: CGPoint(x: 230, y: 107.15), controlPoint1: CGPoint(x: 237.29, y: 115.61), controlPoint2: CGPoint(x: 235.1, y: 109.54))
        iconPath.addLine(to: CGPoint(x: 143.8, y: 66.66))
        iconPath.addCurve(to: CGPoint(x: 130.24, y: 71.56), controlPoint1: CGPoint(x: 138.7, y: 64.27), controlPoint2: CGPoint(x: 132.63, y: 66.46))
        iconPath.close()
        iconPath.move(to: CGPoint(x: 102.8, y: 5.03))
        iconPath.addCurve(to: CGPoint(x: 163.32, y: 22.78), controlPoint1: CGPoint(x: 124.91, y: 5.55), controlPoint2: CGPoint(x: 145.63, y: 11.99))
        iconPath.addCurve(to: CGPoint(x: 225.09, y: 5.1), controlPoint1: CGPoint(x: 180.75, y: 10.79), controlPoint2: CGPoint(x: 202.19, y: 4.15))
        iconPath.addCurve(to: CGPoint(x: 291.12, y: 33.15), controlPoint1: CGPoint(x: 250.89, y: 6.16), controlPoint2: CGPoint(x: 274.02, y: 16.7))
        iconPath.addCurve(to: CGPoint(x: 317.82, y: 27.45), controlPoint1: CGPoint(x: 299.17, y: 29.3), controlPoint2: CGPoint(x: 308.26, y: 27.22))
        iconPath.addCurve(to: CGPoint(x: 374.31, y: 85.61), controlPoint1: CGPoint(x: 349.77, y: 28.2), controlPoint2: CGPoint(x: 375.06, y: 54.24))
        iconPath.addCurve(to: CGPoint(x: 368.61, y: 108.89), controlPoint1: CGPoint(x: 374.11, y: 93.95), controlPoint2: CGPoint(x: 372.07, y: 101.84))
        iconPath.addCurve(to: CGPoint(x: 399.98, y: 178.68), controlPoint1: CGPoint(x: 387.49, y: 126.43), controlPoint2: CGPoint(x: 399.46, y: 151.13))
        iconPath.addCurve(to: CGPoint(x: 380.5, y: 238.9), controlPoint1: CGPoint(x: 400.42, y: 201.18), controlPoint2: CGPoint(x: 393.12, y: 222.07))
        iconPath.addCurve(to: CGPoint(x: 397.14, y: 298.7), controlPoint1: CGPoint(x: 391.09, y: 256.53), controlPoint2: CGPoint(x: 397.14, y: 277))
        iconPath.addCurve(to: CGPoint(x: 397.07, y: 302.2), controlPoint1: CGPoint(x: 397.14, y: 299.87), controlPoint2: CGPoint(x: 397.12, y: 301.05))
        iconPath.addCurve(to: CGPoint(x: 223.48, y: 366.16), controlPoint1: CGPoint(x: 394.5, y: 389.37), controlPoint2: CGPoint(x: 284.77, y: 429.27))
        iconPath.addLine(to: CGPoint(x: 192.91, y: 334.67))
        iconPath.addCurve(to: CGPoint(x: 162.87, y: 323.57), controlPoint1: CGPoint(x: 185.14, y: 326.66), controlPoint2: CGPoint(x: 174.09, y: 322.71))
        iconPath.addCurve(to: CGPoint(x: 156.45, y: 323.82), controlPoint1: CGPoint(x: 160.75, y: 323.74), controlPoint2: CGPoint(x: 158.61, y: 323.82))
        iconPath.addLine(to: CGPoint(x: 75.26, y: 323.82))
        iconPath.addLine(to: CGPoint(x: 75.26, y: 236.87))
        iconPath.addCurve(to: CGPoint(x: 75.32, y: 234.06), controlPoint1: CGPoint(x: 75.26, y: 235.93), controlPoint2: CGPoint(x: 75.28, y: 234.99))
        iconPath.addCurve(to: CGPoint(x: 64.51, y: 207.78), controlPoint1: CGPoint(x: 75.66, y: 224.23), controlPoint2: CGPoint(x: 71.6, y: 214.74))
        iconPath.addLine(to: CGPoint(x: 29.97, y: 173.87))
        iconPath.addCurve(to: CGPoint(x: 36.41, y: 27.28), controlPoint1: CGPoint(x: -15.15, y: 129.57), controlPoint2: CGPoint(x: -5.52, y: 61.99))
        iconPath.addCurve(to: CGPoint(x: 99.23, y: 5), controlPoint1: CGPoint(x: 52.84, y: 13.68), controlPoint2: CGPoint(x: 74.23, y: 5.13))
        iconPath.addCurve(to: CGPoint(x: 102.8, y: 5.03), controlPoint1: CGPoint(x: 100.41, y: 5), controlPoint2: CGPoint(x: 101.61, y: 5))
        iconPath.close()
        dark ? UIColor.systemBlue.setFill() : vermillion.setFill()
        iconPath.fill()
        
        context.restoreGState()

    }

    @objc dynamic public class func drawAppText(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 2286, height: 400), dark: Bool = false, resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 2286, height: 400), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 2286, y: resizedFrame.height / 400)


        //// Color Declarations
        let vermilion_minus = UIColor(red: 0.914, green: 0.424, blue: 0.380, alpha: 1.000)
        let vermillion = UIColor(red: 0.890, green: 0.259, blue: 0.204, alpha: 1.000)
        let blue = UIColor.systemBlue
        let blue_minus = UIColor(red: 0.102, green: 0.529, blue: 1.000, alpha: 1.000)
        
        //// Gradient Declarations
        let gradient = CGGradient(colorsSpace: nil,
                                  colors: [
                                    dark ? blue.cgColor : vermillion.cgColor,
                                    dark ? blue.blended(withFraction: 0.5, of: blue_minus).cgColor : vermillion.blended(withFraction: 0.5, of: vermilion_minus).cgColor,
                                    dark ? blue_minus.cgColor : vermilion_minus.cgColor
                                  ] as CFArray,
                                  locations: [0, 0.53, 1])!

        //// text Drawing
        let textPath = UIBezierPath()
        textPath.move(to: CGPoint(x: 46.63, y: 296.15))
        textPath.addCurve(to: CGPoint(x: 79.67, y: 361.72), controlPoint1: CGPoint(x: 46.93, y: 324.79), controlPoint2: CGPoint(x: 57.94, y: 346.65))
        textPath.addCurve(to: CGPoint(x: 129.46, y: 376.19), controlPoint1: CGPoint(x: 93.85, y: 371.37), controlPoint2: CGPoint(x: 110.45, y: 376.19))
        textPath.addCurve(to: CGPoint(x: 174.51, y: 368.28), controlPoint1: CGPoint(x: 145.46, y: 376.19), controlPoint2: CGPoint(x: 160.47, y: 373.55))
        textPath.addCurve(to: CGPoint(x: 200.53, y: 348.15), controlPoint1: CGPoint(x: 188.54, y: 363), controlPoint2: CGPoint(x: 197.21, y: 356.29))
        textPath.addCurve(to: CGPoint(x: 186.05, y: 324.18), controlPoint1: CGPoint(x: 196.31, y: 340.92), controlPoint2: CGPoint(x: 191.48, y: 332.93))
        textPath.addCurve(to: CGPoint(x: 174.05, y: 304.29), controlPoint1: CGPoint(x: 180.62, y: 315.44), controlPoint2: CGPoint(x: 176.62, y: 308.81))
        textPath.addCurve(to: CGPoint(x: 167.94, y: 292.53), controlPoint1: CGPoint(x: 171.49, y: 299.76), controlPoint2: CGPoint(x: 169.45, y: 295.85))
        textPath.addCurve(to: CGPoint(x: 152.78, y: 303.16), controlPoint1: CGPoint(x: 164.62, y: 297.05), controlPoint2: CGPoint(x: 159.57, y: 300.59))
        textPath.addCurve(to: CGPoint(x: 133.54, y: 305.19), controlPoint1: CGPoint(x: 145.99, y: 305.72), controlPoint2: CGPoint(x: 139.57, y: 306.4))
        textPath.addCurve(to: CGPoint(x: 119.96, y: 295.69), controlPoint1: CGPoint(x: 126.9, y: 303.99), controlPoint2: CGPoint(x: 122.37, y: 300.82))
        textPath.addCurve(to: CGPoint(x: 116.79, y: 269.92), controlPoint1: CGPoint(x: 117.54, y: 290.57), controlPoint2: CGPoint(x: 116.49, y: 281.98))
        textPath.addLine(to: CGPoint(x: 116.79, y: 192.13))
        textPath.addLine(to: CGPoint(x: 179.71, y: 192.13))
        textPath.addLine(to: CGPoint(x: 179.71, y: 127.46))
        textPath.addLine(to: CGPoint(x: 116.34, y: 127.01))
        textPath.addLine(to: CGPoint(x: 117.24, y: 34.76))
        textPath.addLine(to: CGPoint(x: 48.44, y: 80.43))
        textPath.addLine(to: CGPoint(x: 48.44, y: 129.27))
        textPath.addLine(to: CGPoint(x: 0.91, y: 129.27))
        textPath.addLine(to: CGPoint(x: 0, y: 191.23))
        textPath.addLine(to: CGPoint(x: 46.63, y: 191.68))
        textPath.addLine(to: CGPoint(x: 46.63, y: 296.15))
        textPath.close()
        textPath.move(to: CGPoint(x: 220.45, y: 39.28))
        textPath.addLine(to: CGPoint(x: 220.45, y: 374.83))
        textPath.addLine(to: CGPoint(x: 293.78, y: 375.74))
        textPath.addLine(to: CGPoint(x: 294.24, y: 244.59))
        textPath.addCurve(to: CGPoint(x: 297.86, y: 224.24), controlPoint1: CGPoint(x: 294.24, y: 237.36), controlPoint2: CGPoint(x: 295.44, y: 230.57))
        textPath.addCurve(to: CGPoint(x: 307.82, y: 208.19), controlPoint1: CGPoint(x: 300.27, y: 217.91), controlPoint2: CGPoint(x: 303.59, y: 212.56))
        textPath.addCurve(to: CGPoint(x: 322.98, y: 197.79), controlPoint1: CGPoint(x: 312.04, y: 203.82), controlPoint2: CGPoint(x: 317.1, y: 200.35))
        textPath.addCurve(to: CGPoint(x: 342.22, y: 193.94), controlPoint1: CGPoint(x: 328.87, y: 195.22), controlPoint2: CGPoint(x: 335.28, y: 193.94))
        textPath.addCurve(to: CGPoint(x: 375.27, y: 207.51), controlPoint1: CGPoint(x: 356.1, y: 194.24), controlPoint2: CGPoint(x: 367.12, y: 198.77))
        textPath.addCurve(to: CGPoint(x: 387.49, y: 241.88), controlPoint1: CGPoint(x: 383.41, y: 216.25), controlPoint2: CGPoint(x: 387.49, y: 227.71))
        textPath.addLine(to: CGPoint(x: 387.49, y: 374.83))
        textPath.addLine(to: CGPoint(x: 459.92, y: 375.74))
        textPath.addLine(to: CGPoint(x: 459.92, y: 228.76))
        textPath.addCurve(to: CGPoint(x: 433.89, y: 160.48), controlPoint1: CGPoint(x: 459.92, y: 201.33), controlPoint2: CGPoint(x: 451.24, y: 178.57))
        textPath.addCurve(to: CGPoint(x: 366.21, y: 133.34), controlPoint1: CGPoint(x: 416.53, y: 142.39), controlPoint2: CGPoint(x: 393.98, y: 133.34))
        textPath.addCurve(to: CGPoint(x: 291.52, y: 161.83), controlPoint1: CGPoint(x: 330, y: 133.34), controlPoint2: CGPoint(x: 305.1, y: 142.84))
        textPath.addLine(to: CGPoint(x: 291.52, y: 39.28))
        textPath.addLine(to: CGPoint(x: 220.45, y: 39.28))
        textPath.close()
        textPath.move(to: CGPoint(x: 491.15, y: 130.63))
        textPath.addLine(to: CGPoint(x: 491.15, y: 374.83))
        textPath.addLine(to: CGPoint(x: 564.03, y: 374.83))
        textPath.addLine(to: CGPoint(x: 564.03, y: 130.63))
        textPath.addLine(to: CGPoint(x: 491.15, y: 130.63))
        textPath.close()
        textPath.move(to: CGPoint(x: 527.36, y: 108.02))
        textPath.addCurve(to: CGPoint(x: 559.28, y: 96.04), controlPoint1: CGPoint(x: 540.34, y: 108.02), controlPoint2: CGPoint(x: 550.98, y: 104.02))
        textPath.addCurve(to: CGPoint(x: 571.73, y: 65.06), controlPoint1: CGPoint(x: 567.58, y: 88.05), controlPoint2: CGPoint(x: 571.73, y: 77.72))
        textPath.addCurve(to: CGPoint(x: 569.69, y: 51.26), controlPoint1: CGPoint(x: 571.73, y: 60.23), controlPoint2: CGPoint(x: 571.05, y: 55.64))
        textPath.addCurve(to: CGPoint(x: 563.58, y: 39.73), controlPoint1: CGPoint(x: 568.33, y: 46.89), controlPoint2: CGPoint(x: 566.29, y: 43.05))
        textPath.addCurve(to: CGPoint(x: 554.07, y: 30.91), controlPoint1: CGPoint(x: 560.86, y: 36.42), controlPoint2: CGPoint(x: 557.69, y: 33.48))
        textPath.addCurve(to: CGPoint(x: 541.85, y: 25.04), controlPoint1: CGPoint(x: 550.45, y: 28.35), controlPoint2: CGPoint(x: 546.38, y: 26.39))
        textPath.addCurve(to: CGPoint(x: 527.36, y: 23), controlPoint1: CGPoint(x: 537.32, y: 23.68), controlPoint2: CGPoint(x: 532.49, y: 23))
        textPath.addCurve(to: CGPoint(x: 495.68, y: 34.76), controlPoint1: CGPoint(x: 514.39, y: 23), controlPoint2: CGPoint(x: 503.83, y: 26.92))
        textPath.addCurve(to: CGPoint(x: 483.46, y: 65.06), controlPoint1: CGPoint(x: 487.53, y: 42.6), controlPoint2: CGPoint(x: 483.46, y: 52.7))
        textPath.addCurve(to: CGPoint(x: 486.62, y: 82.47), controlPoint1: CGPoint(x: 483.46, y: 71.39), controlPoint2: CGPoint(x: 484.51, y: 77.19))
        textPath.addCurve(to: CGPoint(x: 495.68, y: 96.04), controlPoint1: CGPoint(x: 488.74, y: 87.74), controlPoint2: CGPoint(x: 491.75, y: 92.27))
        textPath.addCurve(to: CGPoint(x: 509.71, y: 104.85), controlPoint1: CGPoint(x: 499.6, y: 99.8), controlPoint2: CGPoint(x: 504.28, y: 102.74))
        textPath.addCurve(to: CGPoint(x: 527.36, y: 108.02), controlPoint1: CGPoint(x: 515.14, y: 106.96), controlPoint2: CGPoint(x: 521.03, y: 108.02))
        textPath.close()
        textPath.move(to: CGPoint(x: 588.93, y: 374.83))
        textPath.addLine(to: CGPoint(x: 659.09, y: 374.83))
        textPath.addLine(to: CGPoint(x: 659.09, y: 238.71))
        textPath.addCurve(to: CGPoint(x: 662.49, y: 218.36), controlPoint1: CGPoint(x: 659.09, y: 231.18), controlPoint2: CGPoint(x: 660.22, y: 224.39))
        textPath.addCurve(to: CGPoint(x: 672.22, y: 203.44), controlPoint1: CGPoint(x: 664.75, y: 212.33), controlPoint2: CGPoint(x: 667.99, y: 207.36))
        textPath.addCurve(to: CGPoint(x: 686.93, y: 194.62), controlPoint1: CGPoint(x: 676.44, y: 199.52), controlPoint2: CGPoint(x: 681.35, y: 196.58))
        textPath.addCurve(to: CGPoint(x: 705.26, y: 191.68), controlPoint1: CGPoint(x: 692.51, y: 192.66), controlPoint2: CGPoint(x: 698.63, y: 191.68))
        textPath.addCurve(to: CGPoint(x: 736.27, y: 203.44), controlPoint1: CGPoint(x: 718.54, y: 191.68), controlPoint2: CGPoint(x: 728.88, y: 195.6))
        textPath.addCurve(to: CGPoint(x: 747.36, y: 236.9), controlPoint1: CGPoint(x: 743.67, y: 211.28), controlPoint2: CGPoint(x: 747.36, y: 222.43))
        textPath.addLine(to: CGPoint(x: 747.36, y: 374.83))
        textPath.addLine(to: CGPoint(x: 818.43, y: 374.83))
        textPath.addLine(to: CGPoint(x: 818.43, y: 223.79))
        textPath.addCurve(to: CGPoint(x: 786.75, y: 150.98), controlPoint1: CGPoint(x: 818.43, y: 194.24), controlPoint2: CGPoint(x: 807.87, y: 169.97))
        textPath.addCurve(to: CGPoint(x: 703.91, y: 122.49), controlPoint1: CGPoint(x: 765.62, y: 131.99), controlPoint2: CGPoint(x: 738.01, y: 122.49))
        textPath.addCurve(to: CGPoint(x: 687.84, y: 123.39), controlPoint1: CGPoint(x: 698.78, y: 122.49), controlPoint2: CGPoint(x: 693.42, y: 122.79))
        textPath.addCurve(to: CGPoint(x: 667.69, y: 127.92), controlPoint1: CGPoint(x: 682.25, y: 124), controlPoint2: CGPoint(x: 675.54, y: 125.51))
        textPath.addCurve(to: CGPoint(x: 645.51, y: 136.96), controlPoint1: CGPoint(x: 659.85, y: 130.33), controlPoint2: CGPoint(x: 652.45, y: 133.34))
        textPath.addCurve(to: CGPoint(x: 624.46, y: 152.34), controlPoint1: CGPoint(x: 638.57, y: 140.58), controlPoint2: CGPoint(x: 631.55, y: 145.7))
        textPath.addCurve(to: CGPoint(x: 606.13, y: 175.4), controlPoint1: CGPoint(x: 617.37, y: 158.97), controlPoint2: CGPoint(x: 611.26, y: 166.66))
        textPath.addCurve(to: CGPoint(x: 593.91, y: 207.96), controlPoint1: CGPoint(x: 601, y: 184.14), controlPoint2: CGPoint(x: 596.93, y: 195))
        textPath.addCurve(to: CGPoint(x: 589.38, y: 250.47), controlPoint1: CGPoint(x: 590.89, y: 220.93), controlPoint2: CGPoint(x: 589.38, y: 235.1))
        textPath.addLine(to: CGPoint(x: 588.93, y: 374.83))
        textPath.close()
        textPath.move(to: CGPoint(x: 844.24, y: 374.83))
        textPath.addLine(to: CGPoint(x: 913.49, y: 375.74))
        textPath.addLine(to: CGPoint(x: 914.4, y: 312.43))
        textPath.addLine(to: CGPoint(x: 941.11, y: 289.36))
        textPath.addCurve(to: CGPoint(x: 958.99, y: 315.14), controlPoint1: CGPoint(x: 943.22, y: 291.77), controlPoint2: CGPoint(x: 949.18, y: 300.37))
        textPath.addCurve(to: CGPoint(x: 986.6, y: 356.29), controlPoint1: CGPoint(x: 968.8, y: 329.91), controlPoint2: CGPoint(x: 978, y: 343.63))
        textPath.addCurve(to: CGPoint(x: 1000.41, y: 374.83), controlPoint1: CGPoint(x: 995.2, y: 368.96), controlPoint2: CGPoint(x: 999.8, y: 375.14))
        textPath.addCurve(to: CGPoint(x: 1009.91, y: 374.16), controlPoint1: CGPoint(x: 1001.01, y: 374.53), controlPoint2: CGPoint(x: 1004.18, y: 374.31))
        textPath.addCurve(to: CGPoint(x: 1030.74, y: 373.7), controlPoint1: CGPoint(x: 1015.65, y: 374.01), controlPoint2: CGPoint(x: 1022.59, y: 373.85))
        textPath.addCurve(to: CGPoint(x: 1054.5, y: 373.48), controlPoint1: CGPoint(x: 1038.89, y: 373.55), controlPoint2: CGPoint(x: 1046.81, y: 373.48))
        textPath.addCurve(to: CGPoint(x: 1074.65, y: 373.48), controlPoint1: CGPoint(x: 1062.2, y: 373.48), controlPoint2: CGPoint(x: 1068.91, y: 373.48))
        textPath.addCurve(to: CGPoint(x: 1082.79, y: 373.93), controlPoint1: CGPoint(x: 1080.38, y: 373.48), controlPoint2: CGPoint(x: 1083.1, y: 373.63))
        textPath.addLine(to: CGPoint(x: 991.81, y: 242.78))
        textPath.addLine(to: CGPoint(x: 1085.96, y: 132.44))
        textPath.addLine(to: CGPoint(x: 1000.41, y: 131.99))
        textPath.addLine(to: CGPoint(x: 913.04, y: 223.34))
        textPath.addLine(to: CGPoint(x: 913.49, y: 39.28))
        textPath.addLine(to: CGPoint(x: 844.24, y: 39.28))
        textPath.addLine(to: CGPoint(x: 844.24, y: 374.83))
        textPath.close()
        textPath.move(to: CGPoint(x: 1267.49, y: 373.48))
        textPath.addLine(to: CGPoint(x: 1310.49, y: 213.84))
        textPath.addLine(to: CGPoint(x: 1345.34, y: 373.48))
        textPath.addLine(to: CGPoint(x: 1431.35, y: 373.48))
        textPath.addLine(to: CGPoint(x: 1501.97, y: 131.08))
        textPath.addLine(to: CGPoint(x: 1433.62, y: 131.08))
        textPath.addLine(to: CGPoint(x: 1389.25, y: 283.94))
        textPath.addLine(to: CGPoint(x: 1353.04, y: 130.63))
        textPath.addLine(to: CGPoint(x: 1266.58, y: 131.08))
        textPath.addLine(to: CGPoint(x: 1225.39, y: 284.39))
        textPath.addLine(to: CGPoint(x: 1181.93, y: 130.63))
        textPath.addLine(to: CGPoint(x: 1111.31, y: 131.08))
        textPath.addLine(to: CGPoint(x: 1181.48, y: 373.48))
        textPath.addLine(to: CGPoint(x: 1267.49, y: 373.48))
        textPath.close()
        textPath.move(to: CGPoint(x: 1530.94, y: 39.28))
        textPath.addLine(to: CGPoint(x: 1530.94, y: 374.83))
        textPath.addLine(to: CGPoint(x: 1604.27, y: 375.74))
        textPath.addLine(to: CGPoint(x: 1604.73, y: 244.59))
        textPath.addCurve(to: CGPoint(x: 1608.35, y: 224.24), controlPoint1: CGPoint(x: 1604.73, y: 237.36), controlPoint2: CGPoint(x: 1605.93, y: 230.57))
        textPath.addCurve(to: CGPoint(x: 1618.31, y: 208.19), controlPoint1: CGPoint(x: 1610.76, y: 217.91), controlPoint2: CGPoint(x: 1614.08, y: 212.56))
        textPath.addCurve(to: CGPoint(x: 1633.47, y: 197.79), controlPoint1: CGPoint(x: 1622.53, y: 203.82), controlPoint2: CGPoint(x: 1627.59, y: 200.35))
        textPath.addCurve(to: CGPoint(x: 1652.71, y: 193.94), controlPoint1: CGPoint(x: 1639.36, y: 195.22), controlPoint2: CGPoint(x: 1645.77, y: 193.94))
        textPath.addCurve(to: CGPoint(x: 1685.76, y: 207.51), controlPoint1: CGPoint(x: 1666.59, y: 194.24), controlPoint2: CGPoint(x: 1677.61, y: 198.77))
        textPath.addCurve(to: CGPoint(x: 1697.98, y: 241.88), controlPoint1: CGPoint(x: 1693.9, y: 216.25), controlPoint2: CGPoint(x: 1697.98, y: 227.71))
        textPath.addLine(to: CGPoint(x: 1697.98, y: 374.83))
        textPath.addLine(to: CGPoint(x: 1770.41, y: 375.74))
        textPath.addLine(to: CGPoint(x: 1770.41, y: 228.76))
        textPath.addCurve(to: CGPoint(x: 1744.38, y: 160.48), controlPoint1: CGPoint(x: 1770.41, y: 201.33), controlPoint2: CGPoint(x: 1761.73, y: 178.57))
        textPath.addCurve(to: CGPoint(x: 1676.7, y: 133.34), controlPoint1: CGPoint(x: 1727.02, y: 142.39), controlPoint2: CGPoint(x: 1704.47, y: 133.34))
        textPath.addCurve(to: CGPoint(x: 1602.01, y: 161.83), controlPoint1: CGPoint(x: 1640.49, y: 133.34), controlPoint2: CGPoint(x: 1615.59, y: 142.84))
        textPath.addLine(to: CGPoint(x: 1602.01, y: 39.28))
        textPath.addLine(to: CGPoint(x: 1530.94, y: 39.28))
        textPath.close()
        textPath.move(to: CGPoint(x: 2066.91, y: 258.16))
        textPath.addCurve(to: CGPoint(x: 2061.02, y: 211.81), controlPoint1: CGPoint(x: 2066.6, y: 240.97), controlPoint2: CGPoint(x: 2064.64, y: 225.52))
        textPath.addCurve(to: CGPoint(x: 2047.67, y: 177.44), controlPoint1: CGPoint(x: 2057.4, y: 198.09), controlPoint2: CGPoint(x: 2052.95, y: 186.63))
        textPath.addCurve(to: CGPoint(x: 2027.98, y: 153.24), controlPoint1: CGPoint(x: 2042.39, y: 168.24), controlPoint2: CGPoint(x: 2035.82, y: 160.18))
        textPath.addCurve(to: CGPoint(x: 2004.66, y: 137.19), controlPoint1: CGPoint(x: 2020.13, y: 146.31), controlPoint2: CGPoint(x: 2012.36, y: 140.96))
        textPath.addCurve(to: CGPoint(x: 1978.41, y: 128.37), controlPoint1: CGPoint(x: 1996.97, y: 133.42), controlPoint2: CGPoint(x: 1988.22, y: 130.48))
        textPath.addCurve(to: CGPoint(x: 1952.15, y: 124.07), controlPoint1: CGPoint(x: 1968.6, y: 126.26), controlPoint2: CGPoint(x: 1959.85, y: 124.83))
        textPath.addCurve(to: CGPoint(x: 1926.12, y: 122.94), controlPoint1: CGPoint(x: 1944.46, y: 123.32), controlPoint2: CGPoint(x: 1935.78, y: 122.94))
        textPath.addCurve(to: CGPoint(x: 1864.33, y: 139.68), controlPoint1: CGPoint(x: 1904.4, y: 122.94), controlPoint2: CGPoint(x: 1883.8, y: 128.52))
        textPath.addCurve(to: CGPoint(x: 1817.03, y: 186.71), controlPoint1: CGPoint(x: 1844.87, y: 150.83), controlPoint2: CGPoint(x: 1829.1, y: 166.51))
        textPath.addCurve(to: CGPoint(x: 1798.92, y: 253.64), controlPoint1: CGPoint(x: 1804.96, y: 206.91), controlPoint2: CGPoint(x: 1798.92, y: 229.22))
        textPath.addCurve(to: CGPoint(x: 1832.42, y: 343.4), controlPoint1: CGPoint(x: 1798.92, y: 290.42), controlPoint2: CGPoint(x: 1810.09, y: 320.34))
        textPath.addCurve(to: CGPoint(x: 1916.17, y: 378), controlPoint1: CGPoint(x: 1854.75, y: 366.47), controlPoint2: CGPoint(x: 1882.67, y: 378))
        textPath.addCurve(to: CGPoint(x: 1965.05, y: 368.96), controlPoint1: CGPoint(x: 1932.76, y: 378), controlPoint2: CGPoint(x: 1949.06, y: 374.99))
        textPath.addCurve(to: CGPoint(x: 1995.84, y: 348.15), controlPoint1: CGPoint(x: 1981.05, y: 362.93), controlPoint2: CGPoint(x: 1991.31, y: 355.99))
        textPath.addLine(to: CGPoint(x: 1995.84, y: 372.12))
        textPath.addLine(to: CGPoint(x: 2066.91, y: 372.12))
        textPath.addLine(to: CGPoint(x: 2066.91, y: 258.16))
        textPath.close()
        textPath.move(to: CGPoint(x: 1959.62, y: 309.71))
        textPath.addCurve(to: CGPoint(x: 1934.95, y: 314.24), controlPoint1: CGPoint(x: 1952.08, y: 312.73), controlPoint2: CGPoint(x: 1943.85, y: 314.24))
        textPath.addCurve(to: CGPoint(x: 1910.05, y: 309.71), controlPoint1: CGPoint(x: 1926.05, y: 314.24), controlPoint2: CGPoint(x: 1917.75, y: 312.73))
        textPath.addCurve(to: CGPoint(x: 1890.59, y: 297.05), controlPoint1: CGPoint(x: 1902.36, y: 306.7), controlPoint2: CGPoint(x: 1895.87, y: 302.48))
        textPath.addCurve(to: CGPoint(x: 1877.92, y: 277.38), controlPoint1: CGPoint(x: 1885.31, y: 291.62), controlPoint2: CGPoint(x: 1881.08, y: 285.07))
        textPath.addCurve(to: CGPoint(x: 1873.16, y: 252.73), controlPoint1: CGPoint(x: 1874.75, y: 269.69), controlPoint2: CGPoint(x: 1873.16, y: 261.48))
        textPath.addCurve(to: CGPoint(x: 1890.59, y: 208.64), controlPoint1: CGPoint(x: 1873.16, y: 234.94), controlPoint2: CGPoint(x: 1878.97, y: 220.25))
        textPath.addCurve(to: CGPoint(x: 1934.73, y: 191.23), controlPoint1: CGPoint(x: 1902.21, y: 197.03), controlPoint2: CGPoint(x: 1916.92, y: 191.23))
        textPath.addCurve(to: CGPoint(x: 1959.62, y: 195.98), controlPoint1: CGPoint(x: 1943.78, y: 191.23), controlPoint2: CGPoint(x: 1952.08, y: 192.81))
        textPath.addCurve(to: CGPoint(x: 1979.09, y: 208.87), controlPoint1: CGPoint(x: 1967.17, y: 199.14), controlPoint2: CGPoint(x: 1973.66, y: 203.44))
        textPath.addCurve(to: CGPoint(x: 1991.76, y: 228.31), controlPoint1: CGPoint(x: 1984.52, y: 214.29), controlPoint2: CGPoint(x: 1988.74, y: 220.77))
        textPath.addCurve(to: CGPoint(x: 1996.29, y: 252.73), controlPoint1: CGPoint(x: 1994.78, y: 235.85), controlPoint2: CGPoint(x: 1996.29, y: 243.99))
        textPath.addCurve(to: CGPoint(x: 1991.76, y: 277.38), controlPoint1: CGPoint(x: 1996.29, y: 261.48), controlPoint2: CGPoint(x: 1994.78, y: 269.69))
        textPath.addCurve(to: CGPoint(x: 1979.09, y: 297.05), controlPoint1: CGPoint(x: 1988.74, y: 285.07), controlPoint2: CGPoint(x: 1984.52, y: 291.62))
        textPath.addCurve(to: CGPoint(x: 1959.62, y: 309.71), controlPoint1: CGPoint(x: 1973.66, y: 302.48), controlPoint2: CGPoint(x: 1967.17, y: 306.7))
        textPath.close()
        textPath.move(to: CGPoint(x: 2132.09, y: 296.15))
        textPath.addCurve(to: CGPoint(x: 2165.14, y: 361.72), controlPoint1: CGPoint(x: 2132.39, y: 324.79), controlPoint2: CGPoint(x: 2143.41, y: 346.65))
        textPath.addCurve(to: CGPoint(x: 2214.93, y: 376.19), controlPoint1: CGPoint(x: 2179.32, y: 371.37), controlPoint2: CGPoint(x: 2195.92, y: 376.19))
        textPath.addCurve(to: CGPoint(x: 2259.97, y: 368.28), controlPoint1: CGPoint(x: 2230.92, y: 376.19), controlPoint2: CGPoint(x: 2245.94, y: 373.55))
        textPath.addCurve(to: CGPoint(x: 2286, y: 348.15), controlPoint1: CGPoint(x: 2274, y: 363), controlPoint2: CGPoint(x: 2282.68, y: 356.29))
        textPath.addCurve(to: CGPoint(x: 2271.51, y: 324.18), controlPoint1: CGPoint(x: 2281.78, y: 340.92), controlPoint2: CGPoint(x: 2276.95, y: 332.93))
        textPath.addCurve(to: CGPoint(x: 2259.52, y: 304.29), controlPoint1: CGPoint(x: 2266.08, y: 315.44), controlPoint2: CGPoint(x: 2262.08, y: 308.81))
        textPath.addCurve(to: CGPoint(x: 2253.41, y: 292.53), controlPoint1: CGPoint(x: 2256.95, y: 299.76), controlPoint2: CGPoint(x: 2254.92, y: 295.85))
        textPath.addCurve(to: CGPoint(x: 2238.24, y: 303.16), controlPoint1: CGPoint(x: 2250.09, y: 297.05), controlPoint2: CGPoint(x: 2245.03, y: 300.59))
        textPath.addCurve(to: CGPoint(x: 2219, y: 305.19), controlPoint1: CGPoint(x: 2231.45, y: 305.72), controlPoint2: CGPoint(x: 2225.04, y: 306.4))
        textPath.addCurve(to: CGPoint(x: 2205.42, y: 295.69), controlPoint1: CGPoint(x: 2212.37, y: 303.99), controlPoint2: CGPoint(x: 2207.84, y: 300.82))
        textPath.addCurve(to: CGPoint(x: 2202.26, y: 269.92), controlPoint1: CGPoint(x: 2203.01, y: 290.57), controlPoint2: CGPoint(x: 2201.95, y: 281.98))
        textPath.addLine(to: CGPoint(x: 2202.26, y: 192.13))
        textPath.addLine(to: CGPoint(x: 2265.18, y: 192.13))
        textPath.addLine(to: CGPoint(x: 2265.18, y: 127.46))
        textPath.addLine(to: CGPoint(x: 2201.8, y: 127.01))
        textPath.addLine(to: CGPoint(x: 2202.71, y: 34.76))
        textPath.addLine(to: CGPoint(x: 2133.9, y: 80.43))
        textPath.addLine(to: CGPoint(x: 2133.9, y: 129.27))
        textPath.addLine(to: CGPoint(x: 2086.37, y: 129.27))
        textPath.addLine(to: CGPoint(x: 2085.47, y: 191.23))
        textPath.addLine(to: CGPoint(x: 2132.09, y: 191.68))
        textPath.addLine(to: CGPoint(x: 2132.09, y: 296.15))
        textPath.close()
        context.saveGState()
        textPath.addClip()
        context.drawLinearGradient(gradient, start: CGPoint(x: 0, y: 200.5), end: CGPoint(x: 2286, y: 200.5), options: [])
        context.restoreGState()
        
        context.restoreGState()

    }




    @objc(AppLogoKitResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
